name: Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        python -m pip install -r requirements.txt
        pyinstaller --onefile --name q3cod4bsp src/__main__.py

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Tests
      run: |
        python -m pip install -r requirements.txt
        pylint src

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Tests
      run: |
        python -m pip install -r requirements.txt
        pytest --cov src
